import type { Metadata } from "next";
import Link from "next/link";
import {
  ShieldCheck,
  CheckCircle,
  XCircle,
  Clock,
  Mail,
  ArrowRight,
} from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL || "https://pixpassport.uk";

export const metadata: Metadata = {
  title: "Refund Policy & Acceptance Guarantee — PixPassport",
  description:
    "Review PixPassport's transparent refund policy, official dimensional acceptance guarantee, eligible refund scenarios, and claims procedure.",
  alternates: {
    canonical: `${SITE_URL}/refund-policy`,
    languages: {
      "en-GB": `${SITE_URL}/refund-policy`,
    },
  },
  openGraph: {
    title: "Refund Policy & Acceptance Guarantee — PixPassport",
    description:
      "Review PixPassport's transparent refund policy, official dimensional acceptance guarantee, eligible refund scenarios, and claims procedure.",
    url: `${SITE_URL}/refund-policy`,
    siteName: "PixPassport",
    locale: "en_GB",
    type: "website",
  },
};

export default function RefundPolicyPage() {
  return (
    <>
      <Navbar ctaText="Create Photo" ctaHref="/passport-size-photo-maker" />

      <main className="flex-1 bg-white text-slate-900" id="main-content">
        {/* Header */}
        <section className="bg-slate-50/80 py-10 sm:py-16 border-b border-slate-200/80" aria-label="Refund Policy header">
          <div className="container-narrow max-w-4xl">
            {/* Breadcrumb */}
            <nav className="text-xs text-slate-600 mb-4" aria-label="Breadcrumb">
              <ol className="flex items-center gap-1.5 list-none p-0 m-0">
                <li>
                  <Link href="/" className="text-slate-600 hover:text-lime-800 transition-colors font-medium">
                    Home
                  </Link>
                </li>
                <li aria-hidden="true">/</li>
                <li className="text-slate-900 font-semibold" aria-current="page">
                  Refund Policy
                </li>
              </ol>
            </nav>

            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-lime-100 border border-lime-300 text-[#365314] text-xs font-bold mb-4">
              <span>🛡️ ACCEPTANCE GUARANTEE</span>
            </div>

            <h1 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold text-[#0F172A] tracking-tight leading-tight mb-3">
              Refund Policy &amp; Acceptance Guarantee
            </h1>
            <p className="text-xs sm:text-sm text-slate-600 font-medium">
              Last Updated: 27 September 2026 · Fair, transparent terms for every customer
            </p>
          </div>
        </section>

        {/* Content Article */}
        <article className="container-narrow max-w-4xl py-12 sm:py-16 space-y-10 text-slate-700 leading-relaxed text-base">
          {/* Guarantee Summary Box */}
          <div className="bg-lime-50/70 border border-lime-300 rounded-2xl p-6 sm:p-8">
            <h2 className="text-xl font-bold text-[#0F172A] mb-3 flex items-center gap-2.5">
              <ShieldCheck className="w-6 h-6 text-[#4D7C0F]" aria-hidden="true" />
              <span>Our Dimensional Acceptance Promise</span>
            </h2>
            <p className="text-slate-800 text-sm sm:text-base leading-relaxed font-medium">
              We stand behind our automated cropping and biometric alignment engine. If a photo generated by PixPassport meeting our input guidelines is rejected by HM Passport Office (HMPO) or an official foreign consulate for technical dimensional reasons, we will promptly re-process your photo for free or issue a 100% refund.
            </p>
          </div>

          {/* 1. Eligible Scenarios */}
          <section aria-labelledby="refund-eligible" className="space-y-4">
            <div className="flex items-center gap-2.5">
              <CheckCircle className="w-6 h-6 text-[#4D7C0F]" aria-hidden="true" />
              <h2 id="refund-eligible" className="text-xl sm:text-2xl font-bold text-[#0F172A] tracking-tight">
                1. Eligible Refund Scenarios
              </h2>
            </div>
            <p>
              You are entitled to a full refund under any of the following circumstances:
            </p>
            <div className="space-y-3">
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
                <strong className="text-slate-900 block font-bold mb-1">Official Government Rejection:</strong>
                <span className="text-sm">Your photo was rejected by HM Passport Office, the US Department of State, or another supported visa authority specifically due to incorrect dimensions, cropping ratio, or technical sizing created by our tool (accompanied by proof of rejection).</span>
              </div>
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
                <strong className="text-slate-900 block font-bold mb-1">Technical System Delivery Failure:</strong>
                <span className="text-sm">You were charged, but technical server errors prevented generation or download of your final digital photo and print sheet, and our support team was unable to provide the files within 24 hours.</span>
              </div>
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
                <strong className="text-slate-900 block font-bold mb-1">Accidental Duplicate Charges:</strong>
                <span className="text-sm">You were billed more than once for the same photo processing session due to network or gateway glitches.</span>
              </div>
            </div>
          </section>

          {/* 2. Ineligible Scenarios */}
          <section aria-labelledby="refund-ineligible" className="space-y-4">
            <div className="flex items-center gap-2.5">
              <XCircle className="w-6 h-6 text-red-600" aria-hidden="true" />
              <h2 id="refund-ineligible" className="text-xl sm:text-2xl font-bold text-[#0F172A] tracking-tight">
                2. Ineligible Refund Scenarios
              </h2>
            </div>
            <p>
              Refunds cannot be granted in the following scenarios, as they depend on the user&rsquo;s original photograph and adherence to basic photography guidance:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-sm sm:text-base">
              <li>
                <strong>User Guideline Violations:</strong> Rejection caused by factors clearly warned against in our guidance checklist (e.g. subject smiling broadly, eyes closed, wearing dark sunglasses or thick frames covering eyes, severe blur, low-resolution original images, or obstructed face).
              </li>
              <li>
                <strong>Change of Mind:</strong> Requesting a refund after successful generation and download of a technically compliant photo simply because you chose not to apply for the passport or changed plans.
              </li>
              <li>
                <strong>Incorrect Country Selection:</strong> Sizing formatted correctly for the country selected by the user (e.g. user selected US 2×2″ instead of UK 35×45 mm).
              </li>
              <li>
                <strong>Failure to Provide Verification:</strong> Claiming rejection without providing the official rejection notice or email from the passport agency.
              </li>
            </ul>
          </section>

          {/* 3. Refund Request Procedure */}
          <section aria-labelledby="refund-procedure" className="space-y-4">
            <h2 id="refund-procedure" className="text-xl sm:text-2xl font-bold text-[#0F172A] tracking-tight">
              3. How to Request a Refund
            </h2>
            <p>
              To submit a refund claim, please email our support team at <a href="mailto:support@pixpassport.uk" className="text-[#365314] font-bold underline">support@pixpassport.uk</a> within 30 days of your purchase date, including the following information:
            </p>
            <ol className="list-decimal pl-5 space-y-2 text-sm sm:text-base">
              <li><strong>Your Full Name &amp; Email Address</strong> used during the transaction.</li>
              <li><strong>Result ID or Transaction Reference</strong> (found on your preview page or bank statement).</li>
              <li><strong>Reason for Request</strong> (explanation of the issue).</li>
              <li><strong>Proof of Rejection</strong> (a screenshot or copy of the rejection email/letter from the passport office, if applicable).</li>
            </ol>
          </section>

          {/* 4. Processing Timelines */}
          <section aria-labelledby="refund-timelines" className="space-y-4">
            <div className="flex items-center gap-2.5">
              <Clock className="w-6 h-6 text-slate-700" aria-hidden="true" />
              <h2 id="refund-timelines" className="text-xl sm:text-2xl font-bold text-[#0F172A] tracking-tight">
                4. Processing Timelines
              </h2>
            </div>
            <p>
              Our support team reviews refund requests within <strong>2 business days</strong>. Once approved:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-sm sm:text-base">
              <li>
                Refunds are credited back directly to the original payment method (card or digital wallet).
              </li>
              <li>
                Funds typically appear in your account within <strong>3 to 5 business days</strong>, depending on your bank or card issuer&rsquo;s processing schedule.
              </li>
            </ul>
          </section>

          {/* 5. Contact Section */}
          <section aria-labelledby="refund-contact" className="bg-slate-900 text-white rounded-2xl p-6 sm:p-8 space-y-4">
            <h2 id="refund-contact" className="text-xl sm:text-2xl font-bold tracking-tight text-white">
              5. Contact Support for Assistance
            </h2>
            <p className="text-slate-300 text-sm sm:text-base leading-relaxed max-w-2xl">
              If you have any difficulty with your photo download or have questions about a refund request, we are here to help:
            </p>
            <div className="flex flex-wrap items-center gap-4 pt-2">
              <a
                href="mailto:support@pixpassport.uk"
                className="inline-flex items-center gap-2 bg-[#4D7C0F] hover:bg-[#3F650C] text-white font-bold text-sm px-5 py-3 rounded-xl transition-colors focus-ring"
              >
                <Mail className="w-4 h-4" aria-hidden="true" />
                <span>support@pixpassport.uk</span>
              </a>
              <Link
                href="/contact-us"
                className="inline-flex items-center gap-2 bg-slate-800 hover:bg-slate-700 text-slate-100 font-semibold text-sm px-5 py-3 rounded-xl border border-slate-700 transition-colors focus-ring"
              >
                <span>Contact Form</span>
                <ArrowRight className="w-4 h-4" aria-hidden="true" />
              </Link>
            </div>
          </section>
        </article>
      </main>

      <Footer />
    </>
  );
}
